version: "3.3"
services:
  mongo:
      image: mongo:7.0
      expose:
        - 27017
      ports:
        - 27017:27017
      volumes:
        - './data:/data/db'
      restart: always
  backendtfg:
      image: backendtfg/backend:latest
      ports:
        - 4002:4002
      restart: always