version: "3.3"
services:
  mongo:
    image: mongo:7.0
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - './data:/data/db'
    restart: always
    networks:
      - db-tier-tfg
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  backendtfg:
    image: backendtfg/backend:latest
    ports:
      - 4002:4002
    restart: always
    networks:
      - db-tier-tfg
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - /home/ea1/tfg_itziar/.env

networks:
  db-tier-tfg:
    driver: bridge
